#$ -S /bin/bash
#$ -N sccaBMI
#$ -V
#$ -e /workdir/users/fnn3/scripts/LOGS/twins_uk/scca_bmiTest.err
#$ -o /workdir/users/fnn3/scripts/LOGS/twins_uk/scca_bmiTest.out
#$ -wd /workdir/users/fnn3/twins_uk/scca/bmi_test
#$ -q long.q@cbsubrito2
#$ -l h_vmem=50G
#$ -pe parenv 1


##This script runs the SCCA code given the SNP and gene abundace tables
##This is the second version using the refactored cca functions


#Set directries
WRK=/workdir/users/fnn3

#SNP and gene abun tables
SNP=$WRK/twins_uk/scca/bmi_test/snp_residuals_mod.csv
#GENE=$WRK/twins_uk/scca/abundance_residuals_mod.csv
SPECIES=$WRK/twins_uk/scca/bmi_test/species_abundance_residuals_mod.txt

#Output
ALPHA=$WRK/twins_uk/scca/bmi_test/twinsUK_species_alpha_results.csv
BETA=$WRK/twins_uk/scca/bmi_test/twinsUK_species_beta_results.csv
CV=$WRK/twins_uk/scca/bmi_test/twinsUK_species_cv_results.csv
CV2=$WRK/twins_uk/scca/bmi_test/twinsUK_species_cv2_results.csv

SCRIPT=$WRK/scripts/snp_metagenomes/statistical_analysis/SCCA2.R

Rscript $SCRIPT -s $SNP -g $SPECIES -a $ALPHA -b $BETA -c $CV -m $CV2 

