#$ -S /bin/bash
#$ -N kraken2
#$ -e /workdir/users/fnn3/scripts/LOGS/twins_uk/kraken.err
#$ -o /workdir/users/fnn3/scripts/LOGS/twins_uk/kraken.out
#$ -t 2-250
#$ -V
#$ -wd /workdir/users/fnn3/twins_uk/taxa/kraken2
#$ -pe parenv 1
#$ -l h_vmem=75G
#$ -q long.q@cbsubrito2

# Run kraken2 to generate report for bracken
# Set paths

WRK=/workdir/users/fnn3

DESIGN_FILE=$WRK/design_files/twins_names.txt
  DESIGN=$(sed -n "${SGE_TASK_ID}p" $DESIGN_FILE)
  NAME=`basename $DESIGN`


DBNAME=$WRK/scripts/tools/kraken2/kraken2_db

DEREP=/workdir/data/twins/3-derep
FQ1=$DEREP/${NAME}_1.fastq
FQ2=$DEREP/${NAME}_2.fastq
OUT=$WRK/twins_uk/taxa/kraken2_c0.1

#Add things to your path, set threads
export PATH=/programs/kraken2.1.0:$PATH
export OMP_NUM_THREADS=1

kraken2 --db $DBNAME --threads 1 --report $OUT/${NAME}.kreport --confidence 0.1 --paired ${FQ1} ${FQ2} > $OUT/${NAME}.kraken
