#$ -S /bin/bash
#$ -N idxstats
#$ -V
#$ -t 1-87
#$ -e /workdir/users/fnn3/scripts/LOGS/twins_uk/idxstats.err
#$ -wd /workdir/users/fnn3/twins_uk/genes/align
#$ -l h_vmem=5G
#$ -q short.q@cbsubrito2

#This script will run samtools idxstats to get alignment stats from indexed bam files. These counts will be used to calculate RPKM

#Set directories
WRK=/workdir/users/fnn3
BAMOUT=$WRK/twins_uk/genes/align/bwa_out/bam
OUT=$WRK/twins_uk/genes/align/bwa_out/idxstats
	if [ ! -d $OUT ]; then mkdir -p $OUT; fi


#Define design file
#DESIGN_FILE=$WRK/design_files/twins_names.csv
#	DESIGN=$(sed -n "${SGE_TASK_ID}p" $DESIGN_FILE)
#	IFS=',' read -ra ARRAY <<< "$DESIGN"
#	NAME=${ARRAY[1]}
#	BATCH=${ARRAY[0]}
	
#LIST=$WRK/design_files/twins_names.txt
LIST=$WRK/twins_uk/genes/abundance/unfiltered/logs/unfinished_twins_rpkm.txt
DESIGN=$(sed -n "${SGE_TASK_ID}p" $LIST)
	NAME=`basename "$DESIGN"`

BAM=$BAMOUT/${NAME}_filtered90_primary.sorted.bam

#Path to SAMtools
#export PATH=/programs/samtools-0.1.19

samtools idxstats ${BAM} > $OUT/${NAME}_filtered90_primary.idxstats.txt
